### ISSUE TITLE
shim errors appeared when running several containers 

### ISSUE THREAD

**Issue by chavafg** [01org/cc-oci-runtime#154]
When trying to launch100 containers, I got several of these errors:
Also the docker-cor.service went to failure state. 
[docker-journal.txt](https://github.com/01org/cc-oci-runtime/files/431621/docker-journal.txt)
[cc-oci-runtime.log.txt](https://github.com/01org/cc-oci-runtime/files/431623/cc-oci-runtime.log.txt)

```
6db699944d5c106a580ba9ed20081c5f3c3626e763fa4f10df6785628562d642
docker: Error response from daemon: shim error: open pid: no such file or directory.
01fd7a382ca1b867cd654fb9c5742c274df22072c7f2c664dd0d8a9adc805f2b
docker: Error response from daemon: fork/exec /usr/bin/cc-oci-runtime.sh: resource temporarily unavailable: "".
```

Taking a look at docker-cor service, I got these errors regarding to container 6db69994:  
```
Aug 23 02:44:30 clr-containers dockerd[1413]: time="2016-08-23T02:44:30.510237936Z" level=debug msg="Calling POST /v1.24/containers/6db699944d5c106a580ba9ed20081c5f3c3626e763fa4f10df6785628562d642/start"
Aug 23 02:44:30 clr-containers dockerd[1413]: time="2016-08-23T02:44:30.510940554Z" level=debug msg="devmapper: activateDeviceIfNeeded(cf80ef447e9ae005edad0f40997b2cd6c78484b6a90819ba1c2d6d6e9c00a2b3)"
Aug 23 02:44:30 clr-containers dockerd[1413]: time="2016-08-23T02:44:30.544955238Z" level=debug msg="container mounted via layerStore: /var/lib/docker/devicemapper/mnt/cf80ef447e9ae005edad0f40997b2cd6c78484b6a90819ba1c2d6d6e9c00a2b3/rootfs"
Aug 23 02:44:30 clr-containers dockerd[1413]: time="2016-08-23T02:44:30.545266939Z" level=debug msg="Assigning addresses for endpoint compassionate_einstein's interface on network bridge"
Aug 23 02:44:30 clr-containers dockerd[1413]: time="2016-08-23T02:44:30.545302902Z" level=debug msg="RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[])"
Aug 23 02:44:30 clr-containers dockerd[1413]: time="2016-08-23T02:44:30.560809130Z" level=debug msg="Assigning addresses for endpoint compassionate_einstein's interface on network bridge"
Aug 23 02:44:30 clr-containers dockerd[1413]: time="2016-08-23T02:44:30.638847205Z" level=debug msg="Programming external connectivity on endpoint compassionate_einstein (f92934906172cd1f25ed7d500f2656fac5b9f2497e6bd1d29367b836d4a875dc)"
Aug 23 02:44:30 clr-containers dockerd[1413]: time="2016-08-23T02:44:30.789139547Z" level=debug msg="sandbox set key processing took 37.843236ms for container 6db699944d5c106a580ba9ed20081c5f3c3626e763fa4f10df6785628562d642"
Aug 23 02:44:30 clr-containers dockerd[1413]: time="2016-08-23T02:44:30.819329263Z" level=error msg="containerd: start container" error="shim error: open pid: no such file or directory" id=6db699944d5c106a580ba9ed20081c5f3c3626e763fa4f10df6785628562d642
Aug 23 02:44:30 clr-containers dockerd[1413]: time="2016-08-23T02:44:30.825724139Z" level=error msg="containerd: deleting container" error="exit status 1"
Aug 23 02:44:30 clr-containers dockerd[1413]: time="2016-08-23T02:44:30.826055271Z" level=error msg="Create container failed with error: shim error: open pid: no such file or directory"
Aug 23 02:44:30 clr-containers dockerd[1413]: time="2016-08-23T02:44:30.868823387Z" level=debug msg="Revoking external connectivity on endpoint compassionate_einstein (f92934906172cd1f25ed7d500f2656fac5b9f2497e6bd1d29367b836d4a875dc)"
Aug 23 02:44:30 clr-containers dockerd[1413]: time="2016-08-23T02:44:30.974861455Z" level=debug msg="Releasing addresses for endpoint compassionate_einstein's interface on network bridge"
Aug 23 02:44:30 clr-containers dockerd[1413]: time="2016-08-23T02:44:30.974914591Z" level=debug msg="ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.35)"
Aug 23 02:44:31 clr-containers dockerd[1413]: time="2016-08-23T02:44:31.007069026Z" level=debug msg="devmapper: UnmountDevice(hash=cf80ef447e9ae005edad0f40997b2cd6c78484b6a90819ba1c2d6d6e9c00a2b3)"
Aug 23 02:44:31 clr-containers dockerd[1413]: time="2016-08-23T02:44:31.007098146Z" level=debug msg="devmapper: Unmount(/var/lib/docker/devicemapper/mnt/cf80ef447e9ae005edad0f40997b2cd6c78484b6a90819ba1c2d6d6e9c00a2b3)"
Aug 23 02:44:31 clr-containers dockerd[1413]: time="2016-08-23T02:44:31.277712337Z" level=debug msg="devmapper: Unmount done"
Aug 23 02:44:31 clr-containers dockerd[1413]: time="2016-08-23T02:44:31.277767181Z" level=debug msg="devmapper: deactivateDevice(cf80ef447e9ae005edad0f40997b2cd6c78484b6a90819ba1c2d6d6e9c00a2b3)"
Aug 23 02:44:31 clr-containers dockerd[1413]: time="2016-08-23T02:44:31.277874322Z" level=debug msg="devmapper: removeDevice START(docker-8:3-3933076-cf80ef447e9ae005edad0f40997b2cd6c78484b6a90819ba1c2d6d6e9c00a2b3)"
Aug 23 02:44:31 clr-containers dockerd[1413]: time="2016-08-23T02:44:31.313192564Z" level=debug msg="devmapper: removeDevice END(docker-8:3-3933076-cf80ef447e9ae005edad0f40997b2cd6c78484b6a90819ba1c2d6d6e9c00a2b3)"
Aug 23 02:44:31 clr-containers dockerd[1413]: time="2016-08-23T02:44:31.313238574Z" level=debug msg="devmapper: deactivateDevice END(cf80ef447e9ae005edad0f40997b2cd6c78484b6a90819ba1c2d6d6e9c00a2b3)"
Aug 23 02:44:31 clr-containers dockerd[1413]: time="2016-08-23T02:44:31.313265274Z" level=debug msg="devmapper: UnmountDevice(hash=cf80ef447e9ae005edad0f40997b2cd6c78484b6a90819ba1c2d6d6e9c00a2b3) END"
Aug 23 02:44:31 clr-containers dockerd[1413]: time="2016-08-23T02:44:31.313443330Z" level=error msg="Handler for POST /v1.24/containers/6db699944d5c106a580ba9ed20081c5f3c3626e763fa4f10df6785628562d642/start returned error: shim error: open pid: no such file or directory"
```
The COR log shows these errors: 
```
2016-08-23T02:44:30.737825Z:6978:cc-oci-runtime:debug:created state file /run/opencontainer/containers/6db699944d5c106a580ba9ed20081c5f3c3626e763fa4f10df6785628562d642/state.json
2016-08-23T02:44:30.737894Z:6978:cc-oci-runtime:debug:running hook command:
2016-08-23T02:44:30.737919Z:6978:cc-oci-runtime:debug:arg: '/usr/bin/dockerd'
2016-08-23T02:44:30.737938Z:6978:cc-oci-runtime:debug:arg: 'libnetwork-setkey'
2016-08-23T02:44:30.737957Z:6978:cc-oci-runtime:debug:arg: '6db699944d5c106a580ba9ed20081c5f3c3626e763fa4f10df6785628562d642'
2016-08-23T02:44:30.737978Z:6978:cc-oci-runtime:debug:arg: '649b4d4390ca88cad18019750426648cff1b48f60a51fd182459010ff9071c01'
2016-08-23T02:44:30.738382Z:6978:cc-oci-runtime:debug:hook process ('/usr/bin/dockerd') running with pid 6981
2016-08-23T02:44:30.790305Z:6978:cc-oci-runtime:debug:Hook pid 6981 ended with exit status 0
2016-08-23T02:44:30.790396Z:6978:cc-oci-runtime:debug:hook process 6981 finished successfully
2016-08-23T02:44:30.790543Z:6978:cc-oci-runtime:debug:Discovering container interfaces
2016-08-23T02:44:30.790595Z:6978:cc-oci-runtime:debug:Interface := [lo]
2016-08-23T02:44:30.790634Z:6978:cc-oci-runtime:debug:Interface := [tunl0]
2016-08-23T02:44:30.790671Z:6978:cc-oci-runtime:debug:Interface := [eth0]
2016-08-23T02:44:30.790707Z:6978:cc-oci-runtime:debug:Interface := [lo]
2016-08-23T02:44:30.790743Z:6978:cc-oci-runtime:debug:Interface := [eth0]
2016-08-23T02:44:30.790797Z:6978:cc-oci-runtime:debug:IP := [172.17.0.35]
2016-08-23T02:44:30.790837Z:6978:cc-oci-runtime:debug:IP := [255.255.0.0]
2016-08-23T02:44:30.791161Z:6978:cc-oci-runtime:critical:failed to spawn [ip -4 route list type unicast dev eth0 exact 0/0]
2016-08-23T02:44:30.791839Z:6978:cc-oci-runtime:critical:failed to spawn [ip link add name beth0 type bridge]
2016-08-23T02:44:30.791907Z:6978:cc-oci-runtime:critical:failed to create network
2016-08-23T02:44:30.791967Z:6980:cc-oci-runtime:debug:allocating 0 bytes for netcfg
2016-08-23T02:44:30.792031Z:6980:cc-oci-runtime:debug:reading netcfg from parent
2016-08-23T02:44:30.792080Z:6980:cc-oci-runtime:debug:adding netcfg to config
2016-08-23T02:44:30.792116Z:6980:cc-oci-runtime:debug:building hypervisor command-line
```

I am attaching the full COR log and docker journal.

**Comment by jodh-intel** [comment]
This looks like an `ENOMEM` issue. I've raised #157 to add further details as the runtime isn't logging sufficient details.

If you can recreate, it would be good to get a full `ps` listing on the machine.

**Comment by chavafg** [comment]
I also thought it was an end of memory issue, but I can see in my system that it has sufficient memory to launch more containers:
```
root@containers-broadwell ~ # free -h
              total        used        free      shared  buff/cache   available
Mem:            15G        3.7G         11G         10M        697M         11G
Swap:          511M          0B        511M
```
The memory was taking after trying to launch the 100 containers, where only 29 containers were launched successfully.  

I am also attaching the ps listing of the machine. 
Also using psstop, there were some qemu-lite process that are running with very low memory usage, maybe they are hanged or dead. 

```
root@containers-broadwell ~ # psstop | grep qemu-lite
16 Kb: qemu-lite-syste (2059) 
16 Kb: qemu-lite-syste (2106) 
12 Kb: qemu-lite-syste (2147) 
16 Kb: qemu-lite-syste (2367) 
104699 Kb: qemu-lite-syste (3018) 
108834 Kb: qemu-lite-syste (3061) 
108857 Kb: qemu-lite-syste (3104) 
106786 Kb: qemu-lite-syste (3145) 
108831 Kb: qemu-lite-syste (3190) 
117043 Kb: qemu-lite-syste (3233) 
110866 Kb: qemu-lite-syste (3274) 
106770 Kb: qemu-lite-syste (3316) 
108826 Kb: qemu-lite-syste (3359) 
112931 Kb: qemu-lite-syste (3400) 
102723 Kb: qemu-lite-syste (3442) 
116993 Kb: qemu-lite-syste (3485) 
119097 Kb: qemu-lite-syste (3527) 
102663 Kb: qemu-lite-syste (3569) 
113010 Kb: qemu-lite-syste (3609) 
104747 Kb: qemu-lite-syste (3655) 
102667 Kb: qemu-lite-syste (3698) 
106725 Kb: qemu-lite-syste (3740) 
108838 Kb: qemu-lite-syste (3781) 
108001 Kb: qemu-lite-syste (3822) 
104582 Kb: qemu-lite-syste (3863) 
103622 Kb: qemu-lite-syste (3903) 
103587 Kb: qemu-lite-syste (3946) 
122350 Kb: qemu-lite-syste (3989) 
112976 Kb: qemu-lite-syste (4031) 
105930 Kb: qemu-lite-syste (4075) 
106748 Kb: qemu-lite-syste (4116) 
110872 Kb: qemu-lite-syste (4157) 
103956 Kb: qemu-lite-syste (4197) 
16 Kb: qemu-lite-syste (4277) 
16 Kb: qemu-lite-syste (4689) 
16 Kb: qemu-lite-syste (4737) 
12 Kb: qemu-lite-syste (4784) 
16 Kb: qemu-lite-syste (4830) 
16 Kb: qemu-lite-syste (4876) 
12 Kb: qemu-lite-syste (4919) 
16 Kb: qemu-lite-syste (4962) 
12 Kb: qemu-lite-syste (5006) 
104088 Kb: qemu-lite-syste (5050) 
16 Kb: qemu-lite-syste (5146) 
16 Kb: qemu-lite-syste (5294) 
16 Kb: qemu-lite-syste (5336) 
```

[ps-aux.txt](https://github.com/01org/cc-oci-runtime/files/432643/ps-aux.txt)

**Comment by jodh-intel** [comment]
Can you check the following:

- `df`
- `sudo systemctl show docker-cor`
- `sudo journalctl -lam --system`

**Comment by chavafg** [comment]
df shows the filesystem with 2% of used space, 
the journal shows some `SIGABRT` 
```
Aug 23 14:12:37 containers-broadwell dockerd[406]: time="2016-08-23T14:12:37.743087322Z" level=error msg="containerd: start container" error="open /var/run/docker/libcontainerd/containerd/cd00cb38c8d42564d8e111d7ac3fb957dfd5b3406ce2c3703e
0054be9c76af19/init/shim-log.json: no such file or directory" id=cd00cb38c8d42564d8e111d7ac3fb957dfd5b3406ce2c3703e0054be9c76af19
Aug 23 14:12:37 containers-broadwell dockerd[406]: runtime/cgo: pthread_create failed: Resource temporarily unavailable
Aug 23 14:12:37 containers-broadwell dockerd[406]: SIGABRT: abort
Aug 23 14:12:37 containers-broadwell dockerd[406]: PC=0x7faa1c2d191f m=40
Aug 23 14:12:37 containers-broadwell dockerd[406]: goroutine 0 [idle]:
Aug 23 14:12:37 containers-broadwell dockerd[406]: goroutine 1 [chan receive, 763 minutes]:
Aug 23 14:12:37 containers-broadwell dockerd[406]: main.daemon(0xc8201923c0, 0x0, 0x0)
Aug 23 14:12:37 containers-broadwell dockerd[406]:      /builddir/build/BUILD/containerd-2e4e484237cf98ce0c5250b41a6f4ff4fc7a7bd8/containerd/main.go:164 +0x9d2
Aug 23 14:12:37 containers-broadwell dockerd[406]: main.main.func2(0xc8201923c0)
Aug 23 14:12:37 containers-broadwell dockerd[406]:      /builddir/build/BUILD/containerd-2e4e484237cf98ce0c5250b41a6f4ff4fc7a7bd8/containerd/main.go:121 +0x25
Aug 23 14:12:37 containers-broadwell dockerd[406]: github.com/codegangsta/cli.(*App).Run(0xc820192280, 0xc82000a0c0, 0xc, 0xc, 0x0, 0x0)
Aug 23 14:12:37 containers-broadwell dockerd[406]:      /builddir/build/BUILD/containerd-2e4e484237cf98ce0c5250b41a6f4ff4fc7a7bd8/vendor/src/github.com/codegangsta/cli/app.go:192 +0x117d
Aug 23 14:12:37 containers-broadwell dockerd[406]: main.main()
Aug 23 14:12:37 containers-broadwell dockerd[406]:      /builddir/build/BUILD/containerd-2e4e484237cf98ce0c5250b41a6f4ff4fc7a7bd8/containerd/main.go:125 +0x320
Aug 23 14:12:37 containers-broadwell dockerd[406]: goroutine 17 [syscall, 763 minutes, locked to thread]:
Aug 23 14:12:37 containers-broadwell dockerd[406]: runtime.goexit()
Aug 23 14:12:37 containers-broadwell dockerd[406]:      /usr/lib/golang/src/runtime/asm_amd64.s:1998 +0x1
Aug 23 14:12:37 containers-broadwell dockerd[406]: goroutine 5 [syscall, 763 minutes]:
Aug 23 14:12:37 containers-broadwell dockerd[406]: os/signal.signal_recv(0x0)
Aug 23 14:12:37 containers-broadwell dockerd[406]:      /usr/lib/golang/src/runtime/sigqueue.go:116 +0x132
Aug 23 14:12:37 containers-broadwell dockerd[406]: os/signal.loop()
Aug 23 14:12:37 containers-broadwell dockerd[406]:      /usr/lib/golang/src/os/signal/signal_unix.go:22 +0x18
Aug 23 14:12:37 containers-broadwell dockerd[406]: created by os/signal.init.1
Aug 23 14:12:37 containers-broadwell dockerd[406]:      /usr/lib/golang/src/os/signal/signal_unix.go:28 +0x37
Aug 23 14:12:37 containers-broadwell dockerd[406]: goroutine 302 [syscall, 1 minutes]:
```

Not sure if something is corrupted in my machines. I already run swupd verify --fix. 

[df.txt](https://github.com/01org/cc-oci-runtime/files/432832/df.txt)
[dockerd-limits.txt](https://github.com/01org/cc-oci-runtime/files/432830/dockerd-limits.txt)
[journal-lam-system.txt](https://github.com/01org/cc-oci-runtime/files/432833/journal-lam-system.txt)
[systemctl-show-docker-cor.txt](https://github.com/01org/cc-oci-runtime/files/432831/systemctl-show-docker-cor.txt)

**Comment by jodh-intel** [comment]
Sniffing around, this problem seems to have been seen a few times with docker.

One piece of advice is to set `TasksMax=infinity` so you could try adding that to `/lib/systemd/system/docker-cor.service`, or...

... or:

```
sudo mkdir -p /etc/systemd/system/docker-cor.service.d/
cat <<EOT | sudo tee /etc/systemd/system/docker-cor.service.d/tasksmax.conf
[Service]
TasksMax=infinity
EOT
```

... then:

```
sudo systemctl daemon-reload
sudo systemctl restart docker-cor
```

**Comment by chavafg** [comment]
`TasksMax=infinity` solved the problem, should we add this as a Best Practice in our Installation guide?

**Comment by jodh-intel** [comment]
I've added this to:

- https://github.com/01org/cc-oci-runtime/wiki/installing-clear-containers-on-fedora-24
- https://github.com/01org/cc-oci-runtime/wiki//Installing-Clear-Containers-on-Ubuntu-16.04
- https://github.com/01org/cc-oci-runtime/wiki/Installing-Clear-Containers-on-Clear-Linux

(Once I've checked with the kernel team, I'll also get the docker package updated in Clr with this setting so that we can drop the instructions from the Clr install instructions).

**Comment by jcvenegas** [comment]
@chavafg @jodh-intel  can we close this issue ?, now that is is documented how to fix it

**Comment by gorozco1** [comment]
@jcvenegas @chavafg @jodh-intel we should add TaskMax=infinity to clear-linux as default's setup don't we ?

**Comment by jcvenegas** [comment]
@gorozco1 agree adding to Clear Linux Serivce file

**Comment by chavafg** [comment]
@jcvenegas, @gorozco1, @jodh-intel, if already documented and added to Clr service file, we can close this issue.

**Comment by jodh-intel** [comment]
@gorozco1, @jcvenegas - I've already done this, but the updated docker hasn't made it into a released build yet. I'll update the wiki for clr to remove the manual `TasksMax=` steps once it appears in a build...

**Comment by jodh-intel** [comment]
I've now updated https://github.com/01org/cc-oci-runtime/wiki/Installing-Clear-Containers-on-Clear-Linux to remove the manual `TasksMax=` steps as it's now enabled by default in Clear Linux.
