### ISSUE TITLE
qemu instances alive after 'docker rm -f'

### ISSUE THREAD

**Issue by aduenasd** [01org/cc-oci-runtime#638]
qemu instances are not being shutdown after 'docker rm -f'

root@clr-skylake # pidof qemu-system-x86_64
root@clr-skylake # docker run -tid clearlinux bash
7085933e09105204369356be0bbdf2681b22a782b566312d7f2b0b0e51ba331f
root@clr-skylake # docker rm -f $(docker ps -aq)
7085933e0910
root@clr-skylake # pidof qemu-system-x86_64
19956
root@clr-skylake  #

I noticed this at:
commit 7188b1c3e22dc4aec016635add6b1a4a6e62ae46
Merge: 2e94d20 19c4503
Author: James O. D. Hunt <james.o.hunt@intel.com>
Date:   Thu Feb 2 09:24:38 2017 +0000

    Merge pull request #613 from amshinde/check-race-support

    make: Add test-program to check -race is supported with go

**Comment by dlespiau** [comment]
Hi,

Which docker version are you using for this test?

**Comment by aduenasd** [comment]
root@clr-skylake ~ # docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.3
 Git commit:   7392c3b0ce0f9d3e918a321c66668c5d1ef4f689
 Built:        Wed Jan 11 05:25:37 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.3
 Git commit:   7392c3b0ce0f9d3e918a321c66668c5d1ef4f689
 Built:        Wed Jan 11 05:25:37 2017
 OS/Arch:      linux/amd64

**Comment by devimc** [comment]
guilty 2b585d9c8a2b1295479faecddea2cd54df1c3a7f

running
```
for i in `seq 0 20`; do  docker run -dti clearlinux sh ; docker rm -f $(docker ps -aq) ; sleep 1; if pidof qemu-lite-system-x86_64; then break ; fi ; done
```
cc-proxy crashes

```
I0202 10:54:34.707926   24817 vm.go:114] [vm 83e7bddb hyperstart] pid 183 exit normally, status 0
I0202 10:54:34.707957   24817 vm.go:114] [vm 83e7bddb hyperstart] exec pid 185, pid 183
I0202 10:54:34.708003   24817 vm.go:114] [vm 83e7bddb hyperstart] can not find exec whose pid is 183
I0202 10:54:34.708075   24817 vm.go:114] [vm 83e7bddb hyperstart] pid 184 exit normally, status 0
I0202 10:54:34.708123   24817 vm.go:114] [vm 83e7bddb hyperstart] exec pid 185, pid 184
I0202 10:54:34.708159   24817 vm.go:114] [vm 83e7bddb hyperstart] can not find exec whose pid is 184
I0202 10:54:34.736140   24817 proxy.go:67] [client #5] connection closed
I0202 10:54:34.742884   24817 vm.go:114] [vm 83e7bddb hyperstart] hyper_loop epoll_wait 2
I0202 10:54:34.742907   24817 vm.go:114] [vm 83e7bddb hyperstart] hyper_handle_event get event 1, he 0x2102a88, fd 12. ops 0x41e0d8
I0202 10:54:34.742929   24817 vm.go:114] [vm 83e7bddb hyperstart] hyper_handle_event event EPOLLIN, he 0x2102a88, fd 12, 0x41e0d8
I0202 10:54:34.742961   24817 vm.go:114] [vm 83e7bddb hyperstart] stderr_loop, seq 0
I0202 10:54:34.743001   24817 vm.go:114] [vm 83e7bddb hyperstart] pts_loop: read 8 data
I0202 10:54:34.743035   24817 vm.go:114] [vm 83e7bddb hyperstart] hyper_modify_event modify event fd 4, 0x41e178, event 5
I0202 10:54:34.743066   24817 vm.go:114] [vm 83e7bddb hyperstart] hyper_handle_event get event 1, he 0x2102a50, fd 11. ops 0x41e0f8
I0202 10:54:34.743087   24817 vm.go:114] [vm 83e7bddb hyperstart] hyper_handle_event event EPOLLIN, he 0x2102a50, fd 11, 0x41e0f8
I0202 10:54:34.743118   24817 vm.go:114] [vm 83e7bddb hyperstart] stdout_loop, seq 1
I0202 10:54:34.743164   24817 vm.go:114] [vm 83e7bddb hyperstart] hyper_loop epoll_wait 1
I0202 10:54:34.743189   24817 vm.go:114] [vm 83e7bddb hyperstart] hyper_handle_event get event 4, he 0x41e178, fd 4. ops 0x41e010
I0202 10:54:34.743208   24817 vm.go:114] [vm 83e7bddb hyperstart] hyper_handle_event event EPOLLOUT, he 0x41e178, fd 4, 0x41e010
I0202 10:54:34.743235   24817 vm.go:114] [vm 83e7bddb io] <- writing to client #5
I0202 10:54:34.743245   24817 vm.go:121] 
00000000  73 68 2d 34 2e 34 23 20                           |sh-4.4# |
error writing I/O data to client: write unix @->@: write: broken pipe
I0202 10:54:34.743289   24817 vm.go:114] [vm 83e7bddb hyperstart] hyper_modify_event modify event fd 4, 0x41e178, event 1
I0202 10:54:34.748507   24817 proxy.go:67] [client #7] client connected
I0202 10:54:34.748672   24817 proxy.go:77] [client #7] attach(containerId=83e7bddbf175ae622fca072e8c36276c5216e8239a1948182812c006c4c94036)
I0202 10:54:34.748940   24817 proxy.go:77] [client #7] hyper(cmd=destroypod, data={})
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x56e554]

goroutine 51 [running]:
panic(0x70dc00, 0xc420010160)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/containers/virtcontainers/hyperstart.(*Hyperstart).writeCtlMessage(0xc4201200c0, 0xc420046d08, 0xc400000004, 0x0)
	/home/X/gopath/src/github.com/containers/virtcontainers/hyperstart/hyperstart.go:254 +0x1f4
github.com/containers/virtcontainers/hyperstart.(*Hyperstart).SendCtlMessage(0xc4201200c0, 0xc4201de300, 0xa, 0xc4201de318, 0x2, 0x8, 0x0, 0x0, 0x0)
	/home/X/gopath/src/github.com/containers/virtcontainers/hyperstart/hyperstart.go:399 +0x139
main.(*vm).SendMessage(0xc42017e150, 0xc4201de300, 0xa, 0xc4201de318, 0x2, 0x8, 0x4, 0x5)
	/home/X/tools/cc-oci-runtime/proxy/vm.go:208 +0x64
main.hyperHandler(0xc42019aea0, 0x24, 0x30, 0x70e7c0, 0xc4201a2990, 0xc42016fae0)
	/home/X/tools/cc-oci-runtime/proxy/proxy.go:264 +0x248
main.(*protocol).handleRequest(0xc420036068, 0xc420046ef0, 0xc42019ae70, 0xc42016fae0, 0x0)
	/home/X/tools/cc-oci-runtime/proxy/protocol.go:95 +0xca
main.(*protocol).Serve(0xc420036068, 0x8e2ce0, 0xc4201a6020, 0x70e7c0, 0xc4201a2990, 0x0, 0x0)
	/home/X/tools/cc-oci-runtime/proxy/protocol.go:129 +0x187
main.(*proxy).serveNewClient(0xc420014780, 0xc420036068, 0x8e2ce0, 0xc4201a6020)
	/home/X/tools/cc-oci-runtime/proxy/proxy.go:352 +0x137
created by main.(*proxy).serve
	/home/X/tools/cc-oci-runtime/proxy/proxy.go:379 +0x4a5
```

**Comment by dlespiau** [comment]
Hum, what makes you think that b585d9 is the faulty commit? that backtrace isn't near that (and it's a new one to me).

**Comment by dlespiau** [comment]
oh actually, it is related, sorry.

 "error writing I/O data to client: write unix @->@: write: broken pipe" is telling me the shim isn't there any more and we signal that the VM is gone. That sounds like a bad idea :/

**Comment by devimc** [comment]
one commit before that one (509b1b3490fff71e59c84ef54ff78d87cb5101f9) cc-proxy does not crash

**Comment by dlespiau** [comment]
That also tells me the shim is terminated before all the stdout/err data has been flushed, but I guess there's nothing we can do when the shim is forcefully terminated
